// SAGA
export const USER_SIGNIN_API_SAGA = "USER_SIGNIN_API_SAGA";
export const PROJECT_CATEGORY_API_SAGA = "PROJECT_CATEGORY_API_SAGA";
export const CREATE_PROJECT_API_SAGA = "CREATE_PROJECT_API_SAGA";
export const GET_ALL_PROJECTS_API_SAGA = "GET_ALL_PROJECTS_API_SAGA";
export const UPDATE_PROJECT_API_SAGE = "UPDATE_PROJECT_API_SAGE";

// REDUCER
export const SAVE_USER_LOGIN = "SAVE_USER_LOGIN";
export const PROJECT_CATEGORY = "PROJECT_CATEGORY";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const SHOW_DRAWER = "SHOW_DRAWER";
export const HIDE_DRAWER = "HIDE_DRAWER";
export const SHOW_EDIT_DRAWER = "SHOW_EDIT_DRAWER";
export const SEND_HANDLE_SUBMIT = "SEND_HANDLE_SUBMIT";
export const INIT_PROJECT_EDIT = "INIT_PROJECT_EDIT";
