// SAGA
export const USER_SIGNIN_API_SAGA = "USER_SIGNIN_API_SAGA";
export const PROJECT_CATEGORY_API_SAGA = "PROJECT_CATEGORY_API_SAGA";

// REDUCER
export const SAVE_USER_LOGIN = "SAVE_USER_LOGIN";
export const PROJECT_CATEGORY = "PROJECT_CATEGORY";
